version: '3.0'
services:
  mariadb:
    container_name: tokyo-subway-mariadb
    hostname: mariadb
    image: mariadb:10.6.8
    ports:
      - '3306:3306'
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=skku
      - MARIADB_PASSWORD=skku
      - MARIADB_DATABASE=tokyosubwaydb
      - MARIADB_ROOT_PASSWORD=rel
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    networks:
      - test-network
  redis:
    container_name: local-redis
    hostname: redis
    image: redis:6.2.5
    ports:
      - '6379:6379'
    restart: always
    networks:
      - test-network
  mongodb:
    container_name: local-mongodb
    hostname: mongodb
    image: mongo:5.0.2
    ports:
      - '27017:27017'
    restart: always
    networks:
      - test-network

networks:
  test-network: