server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/tokyosubwaydb
    username: jangseop
    password: jangseop

spring.sql.init.mode: ALWAYS

spring jpa:
  hibernate.ddl-auto: create
  defer-datasource-initialization: true
