insert into company(name) values ("Tokyo Metro");
insert into company(name) values ("Toei");

insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "긴자선", "Ginza Line", "銀座線", "G");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "마루노우치선", "Marunouchi Line", "丸ノ内線", "M");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "히비야선", "Hibiya Line", "日比谷線", "H");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "도자이선", "Tozai Line", "東西線", "T");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "치요다선", "Chiyoda Line", "千代田線", "C");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "유라쿠초선", "Yurakucho Line", "有楽町線", "Y");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "한조몬선", "Hanzomon Line", "半蔵門線", "Z");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "난보쿠선", "Namboku Line", "南北線", "N");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Tokyo Metro"), "후쿠토신선", "Fukutoshin Line", "副都心線", "F");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Toei"), "아사쿠사선", "Asakusa Line", "浅草線", "A");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Toei"), "미타선", "Mita Line", "三田線", "I");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Toei"), "오에도선", "Oedo Line", "大江戸線", "E");
insert into line(company_id, name_kr, name_en, name_jp, number) values ((select company_id from company where name="Toei"), "신주쿠선", "Shinjuku Line", "新宿線", "S");

insert into station (name_kr, name_en, name_jp) values ('니시마고메', 'unknown', '西馬込');
insert into station (name_kr, name_en, name_jp) values ('마고메', 'unknown', '馬込');
insert into station (name_kr, name_en, name_jp) values ('나카노부', 'unknown', '中延');
insert into station (name_kr, name_en, name_jp) values ('도고시', 'unknown', '戸越');
insert into station (name_kr, name_en, name_jp) values ('고탄다', 'unknown', '五反田');
insert into station (name_kr, name_en, name_jp) values ('다카나와다이', 'unknown', '高輪台');
insert into station (name_kr, name_en, name_jp) values ('센가쿠지', 'unknown', '泉岳寺');
insert into station (name_kr, name_en, name_jp) values ('미타', 'unknown', '三田');
insert into station (name_kr, name_en, name_jp) values ('다이몬', 'unknown', '大門');
insert into station (name_kr, name_en, name_jp) values ('신바시', 'unknown', '新橋');
insert into station (name_kr, name_en, name_jp) values ('히가시긴자', 'unknown', '東銀座');
insert into station (name_kr, name_en, name_jp) values ('다카라초', 'unknown', '宝町');
insert into station (name_kr, name_en, name_jp) values ('니혼바시', 'unknown', '日本橋');
insert into station (name_kr, name_en, name_jp) values ('닌교초', 'unknown', '人形町');
insert into station (name_kr, name_en, name_jp) values ('히가시니혼바시', 'unknown', '東日本橋');
insert into station (name_kr, name_en, name_jp) values ('아사쿠사바시', 'unknown', '浅草橋');
insert into station (name_kr, name_en, name_jp) values ('구라마에', 'unknown', '蔵前');
insert into station (name_kr, name_en, name_jp) values ('아사쿠사', 'unknown', '浅草');
insert into station (name_kr, name_en, name_jp) values ('혼조아즈마바시', 'unknown', '本所吾妻橋');
insert into station (name_kr, name_en, name_jp) values ('오시아게', 'unknown', '押上');
insert into station (name_kr, name_en, name_jp) values ('요요기우에하라', 'unknown', '代々木上原');
insert into station (name_kr, name_en, name_jp) values ('요요기코엔', 'unknown', '代々木公園');
insert into station (name_kr, name_en, name_jp) values ('메이지진구마에(하라주쿠)', 'unknown', '明治神宮前(原宿)');
insert into station (name_kr, name_en, name_jp) values ('오모테산도', 'unknown', '表参道');
insert into station (name_kr, name_en, name_jp) values ('노기자카', 'unknown', '乃木坂');
insert into station (name_kr, name_en, name_jp) values ('아카사카', 'unknown', '赤坂');
insert into station (name_kr, name_en, name_jp) values ('곳카이기지도마에', 'unknown', '国会議事堂前');
insert into station (name_kr, name_en, name_jp) values ('가스미가세키', 'unknown', '霞ヶ関');
insert into station (name_kr, name_en, name_jp) values ('히비야', 'unknown', '日比谷');
insert into station (name_kr, name_en, name_jp) values ('니주바시마에(마루노우치)', 'unknown', '二重橋前(丸の内)');
insert into station (name_kr, name_en, name_jp) values ('오테마치', 'unknown', '大手町');
insert into station (name_kr, name_en, name_jp) values ('신오차노미즈', 'unknown', '新御茶ノ水');
insert into station (name_kr, name_en, name_jp) values ('유시마', 'unknown', '湯島');
insert into station (name_kr, name_en, name_jp) values ('네즈', 'unknown', '根津');
insert into station (name_kr, name_en, name_jp) values ('센다기', 'unknown', '千駄木');
insert into station (name_kr, name_en, name_jp) values ('니시닛포리', 'unknown', '西日暮里');
insert into station (name_kr, name_en, name_jp) values ('마치야', 'unknown', '町屋');
insert into station (name_kr, name_en, name_jp) values ('기타센주', 'unknown', '北千住');
insert into station (name_kr, name_en, name_jp) values ('아야세', 'unknown', '綾瀬');
insert into station (name_kr, name_en, name_jp) values ('기타아야세', 'unknown', '北綾瀬');
insert into station (name_kr, name_en, name_jp) values ('와코시', 'unknown', '和光市');
insert into station (name_kr, name_en, name_jp) values ('지카테쓰나리마스', 'unknown', '地下鉄成増');
insert into station (name_kr, name_en, name_jp) values ('지카테쓰아카쓰카', 'unknown', '地下鉄赤塚');
insert into station (name_kr, name_en, name_jp) values ('헤이와다이', 'unknown', '平和台');
insert into station (name_kr, name_en, name_jp) values ('히카와다이', 'unknown', '氷川台');
insert into station (name_kr, name_en, name_jp) values ('고타케무카이하라', 'unknown', '小竹向原');
insert into station (name_kr, name_en, name_jp) values ('센카와', 'unknown', '千川');
insert into station (name_kr, name_en, name_jp) values ('가나메초', 'unknown', '要町');
insert into station (name_kr, name_en, name_jp) values ('이케부쿠로', 'unknown', '池袋');
insert into station (name_kr, name_en, name_jp) values ('조시가야', 'unknown', '雑司が谷');
insert into station (name_kr, name_en, name_jp) values ('니시와세다', 'unknown', '西早稲田');
insert into station (name_kr, name_en, name_jp) values ('히가시신주쿠', 'unknown', '東新宿');
insert into station (name_kr, name_en, name_jp) values ('신주쿠산초메', 'unknown', '新宿三丁目');
insert into station (name_kr, name_en, name_jp) values ('기타산도', 'unknown', '北参道');
insert into station (name_kr, name_en, name_jp) values ('시부야', 'unknown', '渋谷');
insert into station (name_kr, name_en, name_jp) values ('가이엔마에', 'unknown', '外苑前');
insert into station (name_kr, name_en, name_jp) values ('아오야마잇초메', 'unknown', '青山一丁目');
insert into station (name_kr, name_en, name_jp) values ('아카사카미쓰케', 'unknown', '赤坂見附');
insert into station (name_kr, name_en, name_jp) values ('다메이케산노', 'unknown', '溜池山王');
insert into station (name_kr, name_en, name_jp) values ('도라노몬', 'unknown', '虎ノ門');
insert into station (name_kr, name_en, name_jp) values ('긴자', 'unknown', '銀座');
insert into station (name_kr, name_en, name_jp) values ('교바시', 'unknown', '京橋');
insert into station (name_kr, name_en, name_jp) values ('미쓰코시마에', 'unknown', '三越前');
insert into station (name_kr, name_en, name_jp) values ('간다', 'unknown', '神田');
insert into station (name_kr, name_en, name_jp) values ('스에히로초', 'unknown', '末広町');
insert into station (name_kr, name_en, name_jp) values ('우에노히로코지', 'unknown', '上野広小路');
insert into station (name_kr, name_en, name_jp) values ('우에노', 'unknown', '上野');
insert into station (name_kr, name_en, name_jp) values ('이나리초', 'unknown', '稲荷町');
insert into station (name_kr, name_en, name_jp) values ('다와라마치', 'unknown', '田原町');
insert into station (name_kr, name_en, name_jp) values ('나가타초', 'unknown', '永田町');
insert into station (name_kr, name_en, name_jp) values ('한조몬', 'unknown', '半蔵門');
insert into station (name_kr, name_en, name_jp) values ('구단시타', 'unknown', '九段下');
insert into station (name_kr, name_en, name_jp) values ('진보초', 'unknown', '神保町');
insert into station (name_kr, name_en, name_jp) values ('스이텐구마에', 'unknown', '水天宮前');
insert into station (name_kr, name_en, name_jp) values ('기요스미시라카와', 'unknown', '清澄白河');
insert into station (name_kr, name_en, name_jp) values ('스미요시', 'unknown', '住吉');
insert into station (name_kr, name_en, name_jp) values ('긴시초', 'unknown', '錦糸町');
insert into station (name_kr, name_en, name_jp) values ('나카메구로', 'unknown', '中目黒');
insert into station (name_kr, name_en, name_jp) values ('에비스', 'unknown', '恵比寿');
insert into station (name_kr, name_en, name_jp) values ('히로오', 'unknown', '広尾');
insert into station (name_kr, name_en, name_jp) values ('롯폰기', 'unknown', '六本木');
insert into station (name_kr, name_en, name_jp) values ('가미야초', 'unknown', '神谷町');
insert into station (name_kr, name_en, name_jp) values ('쓰키지', 'unknown', '築地');
insert into station (name_kr, name_en, name_jp) values ('핫초보리', 'unknown', '八丁堀');
insert into station (name_kr, name_en, name_jp) values ('가야바초', 'unknown', '茅場町');
insert into station (name_kr, name_en, name_jp) values ('고덴마초', 'unknown', '小伝馬町');
insert into station (name_kr, name_en, name_jp) values ('아키하바라', 'unknown', '秋葉原');
insert into station (name_kr, name_en, name_jp) values ('나카오카치마치', 'unknown', '仲御徒町');
insert into station (name_kr, name_en, name_jp) values ('이리야', 'unknown', '入谷');
insert into station (name_kr, name_en, name_jp) values ('미노와', 'unknown', '三ノ輪');
insert into station (name_kr, name_en, name_jp) values ('미나미센주', 'unknown', '南千住');
insert into station (name_kr, name_en, name_jp) values ('오기쿠보', 'unknown', '荻窪');
insert into station (name_kr, name_en, name_jp) values ('미나미아사가야', 'unknown', '南阿佐ケ谷');
insert into station (name_kr, name_en, name_jp) values ('신코엔지', 'unknown', '新高円寺');
insert into station (name_kr, name_en, name_jp) values ('히가시코엔지', 'unknown', '東高円寺');
insert into station (name_kr, name_en, name_jp) values ('신나카노', 'unknown', '新中野');
insert into station (name_kr, name_en, name_jp) values ('나카노사카우에', 'unknown', '中野坂上');
insert into station (name_kr, name_en, name_jp) values ('니시신주쿠', 'unknown', '西新宿');
insert into station (name_kr, name_en, name_jp) values ('신주쿠교엔마에', 'unknown', '新宿御苑前');
insert into station (name_kr, name_en, name_jp) values ('요쓰야산초메', 'unknown', '四谷三丁目');
insert into station (name_kr, name_en, name_jp) values ('도쿄', 'unknown', '東京');
insert into station (name_kr, name_en, name_jp) values ('아와지초', 'unknown', '淡路町');
insert into station (name_kr, name_en, name_jp) values ('오차노미즈', 'unknown', '御茶ノ水');
insert into station (name_kr, name_en, name_jp) values ('혼고산초메', 'unknown', '本郷三丁目');
insert into station (name_kr, name_en, name_jp) values ('고라쿠엔', 'unknown', '後楽園');
insert into station (name_kr, name_en, name_jp) values ('묘가다니', 'unknown', '茗荷谷');
insert into station (name_kr, name_en, name_jp) values ('신오쓰카', 'unknown', '新大塚');
insert into station (name_kr, name_en, name_jp) values ('호난초', 'unknown', '方南町');
insert into station (name_kr, name_en, name_jp) values ('나카노후지미초', 'unknown', '中野富士見町');
insert into station (name_kr, name_en, name_jp) values ('나카노신바시', 'unknown', '中野新橋');
insert into station (name_kr, name_en, name_jp) values ('메구로', 'unknown', '目黒');
insert into station (name_kr, name_en, name_jp) values ('시로카네다이', 'unknown', '白金台');
insert into station (name_kr, name_en, name_jp) values ('시로카네타카나와', 'unknown', '白金高輪');
insert into station (name_kr, name_en, name_jp) values ('시바코엔', 'unknown', '芝公園');
insert into station (name_kr, name_en, name_jp) values ('오나리몬', 'unknown', '御成門');
insert into station (name_kr, name_en, name_jp) values ('우치사이와이초', 'unknown', '内幸町');
insert into station (name_kr, name_en, name_jp) values ('스이도바시', 'unknown', '水道橋');
insert into station (name_kr, name_en, name_jp) values ('가스가', 'unknown', '春日');
insert into station (name_kr, name_en, name_jp) values ('하쿠산', 'unknown', '白山');
insert into station (name_kr, name_en, name_jp) values ('센고쿠', 'unknown', '千石');
insert into station (name_kr, name_en, name_jp) values ('스가모', 'unknown', '巣鴨');
insert into station (name_kr, name_en, name_jp) values ('니시스가모', 'unknown', '西巣鴨');
insert into station (name_kr, name_en, name_jp) values ('신이타바시', 'unknown', '新板橋');
insert into station (name_kr, name_en, name_jp) values ('이타바시쿠야쿠쇼마에', 'unknown', '板橋区役所前');
insert into station (name_kr, name_en, name_jp) values ('이타바시혼초', 'unknown', '板橋本町');
insert into station (name_kr, name_en, name_jp) values ('모토하스누마', 'unknown', '本蓮沼');
insert into station (name_kr, name_en, name_jp) values ('시무라사카우에', 'unknown', '志村坂上');
insert into station (name_kr, name_en, name_jp) values ('시무라산초메', 'unknown', '志村三丁目');
insert into station (name_kr, name_en, name_jp) values ('하스네', 'unknown', '蓮根駅');
insert into station (name_kr, name_en, name_jp) values ('니시다이', 'unknown', '西台');
insert into station (name_kr, name_en, name_jp) values ('다카시마다이라', 'unknown', '高島平');
insert into station (name_kr, name_en, name_jp) values ('신타카시마다이라', 'unknown', '新高島平');
insert into station (name_kr, name_en, name_jp) values ('니시타카시마다이라', 'unknown', '西高島平');
insert into station (name_kr, name_en, name_jp) values ('아자부주반', 'unknown', '麻布十番');
insert into station (name_kr, name_en, name_jp) values ('이치가야', 'unknown', '市ケ谷');
insert into station (name_kr, name_en, name_jp) values ('이다바시', 'unknown', '飯田橋');
insert into station (name_kr, name_en, name_jp) values ('도다이마에', 'unknown', '東大前');
insert into station (name_kr, name_en, name_jp) values ('혼코마고메', 'unknown', '本駒込');
insert into station (name_kr, name_en, name_jp) values ('고마고메', 'unknown', '駒込');
insert into station (name_kr, name_en, name_jp) values ('니시가하라', 'unknown', '西ケ原');
insert into station (name_kr, name_en, name_jp) values ('오지', 'unknown', '王子');
insert into station (name_kr, name_en, name_jp) values ('오지카미야', 'unknown', '王子神谷');
insert into station (name_kr, name_en, name_jp) values ('시모', 'unknown', '志茂');
insert into station (name_kr, name_en, name_jp) values ('아카바네이와부치', 'unknown', '赤羽岩淵');
insert into station (name_kr, name_en, name_jp) values ('신주쿠니시구치', 'unknown', '新宿西口');
insert into station (name_kr, name_en, name_jp) values ('와카마쓰카와다', 'unknown', '若松河田');
insert into station (name_kr, name_en, name_jp) values ('우시고메야나기초', 'unknown', '牛込柳町');
insert into station (name_kr, name_en, name_jp) values ('우시고메카구라자카', 'unknown', '牛込神楽坂');
insert into station (name_kr, name_en, name_jp) values ('우에노오카치마치', 'unknown', '上野御徒町');
insert into station (name_kr, name_en, name_jp) values ('신오카치마치', 'unknown', '新御徒町');
insert into station (name_kr, name_en, name_jp) values ('료고쿠', 'unknown', '両国');
insert into station (name_kr, name_en, name_jp) values ('모리시타', 'unknown', '森下');
insert into station (name_kr, name_en, name_jp) values ('몬젠나카초', 'unknown', '門前仲町');
insert into station (name_kr, name_en, name_jp) values ('쓰키시마', 'unknown', '月島');
insert into station (name_kr, name_en, name_jp) values ('가치도키', 'unknown', '勝どき');
insert into station (name_kr, name_en, name_jp) values ('시오도메', 'unknown', '汐留');
insert into station (name_kr, name_en, name_jp) values ('아카바네바시', 'unknown', '赤羽橋');
insert into station (name_kr, name_en, name_jp) values ('고쿠리쓰쿄지조', 'unknown', '国立競技場');
insert into station (name_kr, name_en, name_jp) values ('요요기', 'unknown', '代々木');
insert into station (name_kr, name_en, name_jp) values ('도초마에', 'unknown', '都庁前');
insert into station (name_kr, name_en, name_jp) values ('히가시나카노', 'unknown', '東中野');
insert into station (name_kr, name_en, name_jp) values ('나카이', 'unknown', '中井');
insert into station (name_kr, name_en, name_jp) values ('오치아이미나미나가사키', 'unknown', '落合南長崎');
insert into station (name_kr, name_en, name_jp) values ('신에고타', 'unknown', '新江古田');
insert into station (name_kr, name_en, name_jp) values ('네리마', 'unknown', '練馬');
insert into station (name_kr, name_en, name_jp) values ('도시마엔', 'unknown', '豊島園');
insert into station (name_kr, name_en, name_jp) values ('네리마카스가초', 'unknown', '練馬春日町');
insert into station (name_kr, name_en, name_jp) values ('히카리가오카', 'unknown', '光が丘');
insert into station (name_kr, name_en, name_jp) values ('아케보노바시', 'unknown', '曙橋');
insert into station (name_kr, name_en, name_jp) values ('오가와마치', 'unknown', '小川町');
insert into station (name_kr, name_en, name_jp) values ('이와모토초', 'unknown', '岩本町');
insert into station (name_kr, name_en, name_jp) values ('바쿠로요코야마', 'unknown', '馬喰横山');
insert into station (name_kr, name_en, name_jp) values ('하마초', 'unknown', '浜町');
insert into station (name_kr, name_en, name_jp) values ('기쿠카와', 'unknown', '菊川');
insert into station (name_kr, name_en, name_jp) values ('니시오지마', 'unknown', '西大島');
insert into station (name_kr, name_en, name_jp) values ('오지마', 'unknown', '大島');
insert into station (name_kr, name_en, name_jp) values ('히가시오지마', 'unknown', '東大島');
insert into station (name_kr, name_en, name_jp) values ('후나보리', 'unknown', '船堀');
insert into station (name_kr, name_en, name_jp) values ('이치노에', 'unknown', '一之江');
insert into station (name_kr, name_en, name_jp) values ('미즈에', 'unknown', '瑞江');
insert into station (name_kr, name_en, name_jp) values ('시노자키', 'unknown', '篠崎');
insert into station (name_kr, name_en, name_jp) values ('모토야와타', 'unknown', '本八幡');
insert into station (name_kr, name_en, name_jp) values ('나카노', 'unknown', '中野');
insert into station (name_kr, name_en, name_jp) values ('오치아이', 'unknown', '落合');
insert into station (name_kr, name_en, name_jp) values ('다카다노바바', 'unknown', '高田馬場');
insert into station (name_kr, name_en, name_jp) values ('와세다', 'unknown', '早稲田');
insert into station (name_kr, name_en, name_jp) values ('가구라자카', 'unknown', '神楽坂');
insert into station (name_kr, name_en, name_jp) values ('다케바시', 'unknown', '竹橋');
insert into station (name_kr, name_en, name_jp) values ('기바', 'unknown', '木場');
insert into station (name_kr, name_en, name_jp) values ('도요초', 'unknown', '東陽町');
insert into station (name_kr, name_en, name_jp) values ('미나미스나마치', 'unknown', '南砂町');
insert into station (name_kr, name_en, name_jp) values ('니시카사이', 'unknown', '西葛西');
insert into station (name_kr, name_en, name_jp) values ('가사이', 'unknown', '葛西');
insert into station (name_kr, name_en, name_jp) values ('우라야스', 'unknown', '浦安');
insert into station (name_kr, name_en, name_jp) values ('미나미교토쿠', 'unknown', '南行徳');
insert into station (name_kr, name_en, name_jp) values ('교토쿠', 'unknown', '行徳');
insert into station (name_kr, name_en, name_jp) values ('묘덴', 'unknown', '妙典');
insert into station (name_kr, name_en, name_jp) values ('바라키나카야마', 'unknown', '原木中山');
insert into station (name_kr, name_en, name_jp) values ('니시후나바시', 'unknown', '西船橋');
insert into station (name_kr, name_en, name_jp) values ('히가시이케부쿠로', 'unknown', '東池袋');
insert into station (name_kr, name_en, name_jp) values ('고코쿠지', 'unknown', '護国寺');
insert into station (name_kr, name_en, name_jp) values ('에도가와바시', 'unknown', '江戸川橋');
insert into station (name_kr, name_en, name_jp) values ('고지마치', 'unknown', '麹町');
insert into station (name_kr, name_en, name_jp) values ('사쿠라다몬', 'unknown', '桜田門');
insert into station (name_kr, name_en, name_jp) values ('유라쿠초', 'unknown', '有楽町');
insert into station (name_kr, name_en, name_jp) values ('신토미초', 'unknown', '新富町');
insert into station (name_kr, name_en, name_jp) values ('도요스', 'unknown', '豊洲');
insert into station (name_kr, name_en, name_jp) values ('다쓰미', 'unknown', '辰巳');
insert into station (name_kr, name_en, name_jp) values ('토라노몬힐즈', 'unknown', '虎ノ門ヒルズ');
insert into station (name_kr, name_en, name_jp) values ('카스미가세키', 'unknown', '霞ケ関');
insert into station (name_kr, name_en, name_jp) values ('신주쿠', 'unknown', '新宿');
insert into station (name_kr, name_en, name_jp) values ('긴자잇초메', 'unknown', '銀座一丁目');
insert into station (name_kr, name_en, name_jp) values ('신키바', 'unknown', '新木場');
insert into station (name_kr, name_en, name_jp) values ('니시신주쿠고초메', 'unknown', '西新宿五丁目');
insert into station (name_kr, name_en, name_jp) values ('츠키지시조', 'unknown', '築地市場');
insert into station (name_kr, name_en, name_jp) values ('요츠야', 'unknown', '四ツ谷');
insert into station (name_kr, name_en, name_jp) values ('롯폰기잇초메', 'unknown', '六本木一丁目');

insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='西馬込'), 'A01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='馬込'), 'A02', 1.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='中延'), 'A03', 2.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='戸越'), 'A04', 3.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='五反田'), 'A05', 4.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='高輪台'), 'A06', 5.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='泉岳寺'), 'A07', 6.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='三田'), 'A08', 8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='大門'), 'A09', 9.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='新橋'), 'A10', 10.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='東銀座'), 'A11', 11.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='宝町'), 'A12', 12.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='日本橋'), 'A13', 13, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='人形町'), 'A14', 13.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='東日本橋'), 'A15', 14.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='浅草橋'), 'A16', 15.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='蔵前'), 'A17', 15.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='浅草'), 'A18', 16.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='本所吾妻橋'), 'A19', 17.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='A'), (select station_id from station where name_jp='押上'), 'A20', 18.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='代々木上原'), 'C01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='代々木公園'), 'C02', 1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='明治神宮前(原宿)'), 'C03', 2.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='表参道'), 'C04', 3.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='乃木坂'), 'C05', 4.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='赤坂'), 'C06', 5.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='国会議事堂前'), 'C07', 6.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='霞ヶ関'), 'C08', 7.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='日比谷'), 'C09', 8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='二重橋前(丸の内)'), 'C10', 8.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='大手町'), 'C11', 9.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='新御茶ノ水'), 'C12', 10.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='湯島'), 'C13', 11.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='根津'), 'C14', 13.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='千駄木'), 'C15', 14.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='西日暮里'), 'C16', 15, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='町屋'), 'C17', 16.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='北千住'), 'C18', 19.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='綾瀬'), 'C19', 21.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='綾瀬'), 'C19', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='C'), (select station_id from station where name_jp='北綾瀬'), 'C20', 2.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='和光市'), 'F01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='地下鉄成増'), 'F02', 2.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='地下鉄赤塚'), 'F03', 3.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='平和台'), 'F04', 5.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='氷川台'), 'F05', 6.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='小竹向原'), 'F06', 8.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='千川'), 'F07', 9.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='要町'), 'F08', 10.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='池袋'), 'F09', 11.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='雑司が谷'), 'F10', 13.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='西早稲田'), 'F11', 14.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='東新宿'), 'F12', 15.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='新宿三丁目'), 'F13', 16.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='北参道'), 'F14', 18, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='明治神宮前(原宿)'), 'F15', 19.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='F'), (select station_id from station where name_jp='渋谷'), 'F16', 20.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='渋谷'), 'G01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='表参道'), 'G02', 1.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='外苑前'), 'G03', 1.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='青山一丁目'), 'G04', 2.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='赤坂見附'), 'G05', 3.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='溜池山王'), 'G06', 4.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='虎ノ門'), 'G07', 5.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='新橋'), 'G08', 6.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='銀座'), 'G09', 7.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='京橋'), 'G10', 7.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='日本橋'), 'G11', 8.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='三越前'), 'G12', 9.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='神田'), 'G13', 9.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='末広町'), 'G14', 10.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='上野広小路'), 'G15', 11.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='上野'), 'G16', 12, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='稲荷町'), 'G17', 12.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='田原町'), 'G18', 13.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='G'), (select station_id from station where name_jp='浅草'), 'G19', 14.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='渋谷'), 'Z01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='表参道'), 'Z02', 1.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='青山一丁目'), 'Z03', 2.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='永田町'), 'Z04', 4.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='半蔵門'), 'Z05', 5.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='九段下'), 'Z06', 6.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='神保町'), 'Z07', 7.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='大手町'), 'Z08', 8.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='三越前'), 'Z09', 9.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='水天宮前'), 'Z10', 10.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='清澄白河'), 'Z11', 12.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='住吉'), 'Z12', 14.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='錦糸町'), 'Z13', 15.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Z'), (select station_id from station where name_jp='押上'), 'Z14', 16.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='中目黒'), 'H01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='恵比寿'), 'H02', 1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='広尾'), 'H03', 2.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='六本木'), 'H04', 4.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='神谷町'), 'H05', 5.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='虎ノ門ヒルズ'), 'H06', 6.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='霞ケ関'), 'H07', 7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='日比谷'), 'H08', 8.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='銀座'), 'H09', 8.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='東銀座'), 'H10', 9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='築地'), 'H11', 9.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='八丁堀'), 'H12', 10.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='茅場町'), 'H13', 11.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='人形町'), 'H14', 12, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='小伝馬町'), 'H15', 12.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='秋葉原'), 'H16', 13.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='仲御徒町'), 'H17', 14.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='上野'), 'H18', 15, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='入谷'), 'H19', 16.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='三ノ輪'), 'H20', 17.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='南千住'), 'H21', 18.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='H'), (select station_id from station where name_jp='北千住'), 'H22', 20.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='荻窪'), 'M01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='南阿佐ケ谷'), 'M02', 1.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='新高円寺'), 'M03', 2.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='東高円寺'), 'M04', 3.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='新中野'), 'M05', 4.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='中野坂上'), 'M06', 5.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='西新宿'), 'M07', 6.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='新宿'), 'M08', 7.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='新宿三丁目'), 'M09', 7.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='新宿御苑前'), 'M10', 8.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='四谷三丁目'), 'M11', 9.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='四ツ谷'), 'M12', 10.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='赤坂見附'), 'M13', 11.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='国会議事堂前'), 'M14', 12.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='霞ケ関'), 'M15', 13.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='銀座'), 'M16', 14.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='東京'), 'M17', 15.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='大手町'), 'M18', 16.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='淡路町'), 'M19', 17, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='御茶ノ水'), 'M20', 17.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='本郷三丁目'), 'M21', 18.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='後楽園'), 'M22', 19.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='茗荷谷'), 'M23', 21.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='新大塚'), 'M24', 22.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='池袋'), 'M25', 24.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='方南町'), 'Mb03', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='中野富士見町'), 'Mb04', 1.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='中野新橋'), 'Mb05', 1.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='M'), (select station_id from station where name_jp='中野坂上'), 'M06', 3.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='目黒'), 'I01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='白金台'), 'I02', 1.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='白金高輪'), 'I03', 2.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='三田'), 'I04', 4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='芝公園'), 'I05', 4.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='御成門'), 'I06', 5.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='内幸町'), 'I07', 6.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='日比谷'), 'I08', 7.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='大手町'), 'I09', 8.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='神保町'), 'I10', 9.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='水道橋'), 'I11', 10.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='春日'), 'I12', 11.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='白山'), 'I13', 12.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='千石'), 'I14', 13.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='巣鴨'), 'I15', 14.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='西巣鴨'), 'I16', 16, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='新板橋'), 'I17', 17, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='板橋区役所前'), 'I18', 17.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='板橋本町'), 'I19', 19.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='本蓮沼'), 'I20', 20, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='志村坂上'), 'I21', 21.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='志村三丁目'), 'I22', 22, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='蓮根駅'), 'I23', 23.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='西台'), 'I24', 24, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='高島平'), 'I25', 25, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='新高島平'), 'I26', 25.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='I'), (select station_id from station where name_jp='西高島平'), 'I27', 26.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='目黒'), 'N01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='白金台'), 'N02', 1.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='白金高輪'), 'N03', 2.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='麻布十番'), 'N04', 3.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='六本木一丁目'), 'N05', 4.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='溜池山王'), 'N06', 5.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='永田町'), 'N07', 6.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='四ツ谷'), 'N08', 7.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='市ケ谷'), 'N09', 8.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='飯田橋'), 'N10', 10, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='後楽園'), 'N11', 11.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='東大前'), 'N12', 12.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='本駒込'), 'N13', 13.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='駒込'), 'N14', 15, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='西ケ原'), 'N15', 16.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='王子'), 'N16', 17.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='王子神谷'), 'N17', 18.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='志茂'), 'N18', 20.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='N'), (select station_id from station where name_jp='赤羽岩淵'), 'N19', 21.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='新宿西口'), 'E01', 0.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='東新宿'), 'E02', 2.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='若松河田'), 'E03', 3.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='牛込柳町'), 'E04', 3.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='牛込神楽坂'), 'E05', 4.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='飯田橋'), 'E06', 5.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='春日'), 'E07', 6.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='本郷三丁目'), 'E08', 7.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='上野御徒町'), 'E09', 8.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='新御徒町'), 'E10', 9.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='蔵前'), 'E11', 10.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='両国'), 'E12', 11.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='森下'), 'E13', 12.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='清澄白河'), 'E14', 13.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='門前仲町'), 'E15', 14.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='月島'), 'E16', 15.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='勝どき'), 'E17', 16.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='築地市場'), 'E18', 18.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='汐留'), 'E19', 19.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='大門'), 'E20', 20, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='赤羽橋'), 'E21', 21.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='麻布十番'), 'E22', 22.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='六本木'), 'E23', 23.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='青山一丁目'), 'E24', 24.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='国立競技場'), 'E25', 25.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='代々木'), 'E26', 27.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='新宿'), 'E27', 27.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='都庁前'), 'E28', 28.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='西新宿五丁目'), 'E29', 29.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='中野坂上'), 'E30', 30.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='東中野'), 'E31', 31.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='中井'), 'E32', 32.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='落合南長崎'), 'E33', 33.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='新江古田'), 'E34', 35.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='練馬'), 'E35', 36.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='豊島園'), 'E36', 37.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='練馬春日町'), 'E37', 39.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='E'), (select station_id from station where name_jp='光が丘'), 'E38', 40.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='新宿'), 'S01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='新宿三丁目'), 'S02', 0.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='曙橋'), 'S03', 2.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='市ケ谷'), 'S04', 3.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='九段下'), 'S05', 5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='神保町'), 'S06', 5.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='小川町'), 'S07', 6.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='岩本町'), 'S08', 7.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='馬喰横山'), 'S09', 8.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='浜町'), 'S10', 8.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='森下'), 'S11', 9.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='菊川'), 'S12', 10.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='住吉'), 'S13', 11.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='西大島'), 'S14', 12.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='大島'), 'S15', 12.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='東大島'), 'S16', 14.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='船堀'), 'S17', 15.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='一之江'), 'S18', 17.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='瑞江'), 'S19', 19.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='篠崎'), 'S20', 20.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='S'), (select station_id from station where name_jp='本八幡'), 'S21', 23.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='中野'), 'T01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='落合'), 'T02', 2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='高田馬場'), 'T03', 3.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='早稲田'), 'T04', 5.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='神楽坂'), 'T05', 6.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='飯田橋'), 'T06', 8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='九段下'), 'T07', 8.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='竹橋'), 'T08', 9.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='大手町'), 'T09', 10.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='日本橋'), 'T10', 11.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='茅場町'), 'T11', 12, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='門前仲町'), 'T12', 13.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='木場'), 'T13', 14.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='東陽町'), 'T14', 15.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='南砂町'), 'T15', 17, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='西葛西'), 'T16', 19.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='葛西'), 'T17', 20.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='浦安'), 'T18', 22.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='南行徳'), 'T19', 24, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='行徳'), 'T20', 25.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='妙典'), 'T21', 26.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='原木中山'), 'T22', 28.9, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='T'), (select station_id from station where name_jp='西船橋'), 'T23', 30.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='和光市'), 'Y01', 0, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='地下鉄成増'), 'Y02', 2.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='地下鉄赤塚'), 'Y03', 3.6, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='平和台'), 'Y04', 5.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='氷川台'), 'Y05', 6.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='小竹向原'), 'Y06', 8.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='千川'), 'Y07', 9.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='要町'), 'Y08', 10.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='池袋'), 'Y09', 11.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='東池袋'), 'Y10', 12.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='護国寺'), 'Y11', 13.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='江戸川橋'), 'Y12', 14.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='飯田橋'), 'Y13', 16.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='市ケ谷'), 'Y14', 17.5, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='麹町'), 'Y15', 18.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='永田町'), 'Y16', 19.3, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='桜田門'), 'Y17', 20.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='有楽町'), 'Y18', 21.2, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='銀座一丁目'), 'Y19', 21.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='新富町'), 'Y20', 22.4, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='月島'), 'Y21', 23.7, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='豊洲'), 'Y22', 25.1, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='辰巳'), 'Y23', 26.8, '00:00:00');
insert into line_station (line_id, station_id, number, distance, depart_at) values ((select line_id from line where number='Y'), (select station_id from station where name_jp='新木場'), 'Y24', 28.3, '00:00:00');
